"""
Formal Markdown Compliance & Audit Reporter conforming to Bangladesh Bank Section 8.1.3.
"""

from typing import Optional
from mfs_checker.models import ComplianceScorecard, RuleStatus, Severity, ComplianceTier

def generate_markdown_report(scorecard: ComplianceScorecard, file_path: Optional[str] = None) -> str:
    """Generate professional GitHub Flavored Markdown audit report."""
    md = []
    md.append(f"# Regulatory Cybersecurity Audit Report")
    md.append(f"**Governing Authority**: Bangladesh Bank (Payment Systems Department & ICT Department)")
    md.append(f"**Regulatory Framework**: Bangladesh Bank Cybersecurity Framework Version 1.0 (February 2025)")
    md.append(f"**Audit Subject**: `{scorecard.app_name}` (`{scorecard.package_name}`)")
    md.append(f"**Audit Scope**: Static Analysis & Machine Learning Evaluation of Android Client Binary")
    md.append(f"**Date Generated**: September 2026\n")

    md.append("---")
    md.append("## 1. Executive Summary & Regulatory Classification\n")
    md.append(f"| Evaluation Parameter | Result / Metric |")
    md.append(f"| :--- | :--- |")
    md.append(f"| **Application Package** | `{scorecard.package_name}` |")
    md.append(f"| **Version** | `{scorecard.version_name}` (Code: `{scorecard.version_code}`) |")
    md.append(f"| **Binary Size** | {scorecard.apk_size_mb:.2f} MB |")
    md.append(f"| **Binary SHA-256** | `{scorecard.sha256_hash}` |")
    md.append(f"| **Cybersecurity Maturity Score** | **{scorecard.maturity_score:.1f} / 100.0** |")
    md.append(f"| **Regulatory Classification** | **{scorecard.tier.value}** |\n")

    if scorecard.tier == ComplianceTier.TIER_3_HIGH_RISK:
        md.append("> [!CAUTION]")
        md.append("> **IMMEDIATE REGULATORY ESCALATION REQUIRED (Clause 8.1.2.1)**:")
        md.append(f"> This application accumulated {scorecard.critical_violations} CRITICAL violations and achieved a Maturity Score below the 70.0 threshold. Under Bangladesh Bank Cybersecurity Framework Clause 8.1.2.1, critical security deficiencies must be escalated and mitigated immediately before public distribution.\n")
    elif scorecard.tier == ComplianceTier.TIER_2_CONDITIONAL:
        md.append("> [!WARNING]")
        md.append("> **SUBSTANTIALLY COMPLIANT - REMEDIATION REQUIRED**:")
        md.append("> The application demonstrates baseline security mechanisms, but non-critical compliance gaps exist. Remediation should be verified in the next development cycle.\n")
    else:
        md.append("> [!NOTE]")
        md.append("> **COMPLIANT (TIER 1)**:")
        md.append("> The application satisfies Bangladesh Bank Cybersecurity Framework v1.0 static compliance baselines with no critical vulnerabilities detected.\n")

    md.append("---")
    md.append("## 2. Regulatory Clause Audit Breakdown\n")
    md.append("| Rule ID | Bangladesh Bank Clause | Regulatory Scope | Status | Severity | Penalty |")
    md.append("| :--- | :--- | :--- | :--- | :--- | :--- |")

    for r in scorecard.rule_results:
        status_badge = "✅ PASSED" if r.status == RuleStatus.PASSED else ("❌ FAILED" if r.status == RuleStatus.FAILED else "⚠️ WARNING")
        md.append(f"| **{r.rule_id}** | Clause {r.clause} | {r.title} | {status_badge} | `{r.severity.value}` | -{r.penalty} |")

    md.append("\n---")
    md.append("## 3. Detailed Findings & Remediation Directives\n")

    for r in scorecard.rule_results:
        if r.status in [RuleStatus.FAILED, RuleStatus.WARNING]:
            md.append(f"### [{r.rule_id}] {r.title}")
            md.append(f"- **Bangladesh Bank Clause**: `{r.clause}` ({r.function} - {r.category})")
            md.append(f"- **Severity**: `{r.severity.value}` | **Penalty Applied**: `-{r.penalty} points`")
            md.append(f"- **Regulatory Observation**: {r.details}")

            if r.findings:
                md.append(f"- **Evidence Findings**:")
                for f in r.findings:
                    md.append(f"  * {f.description}")
                    if f.code_snippet:
                        md.append(f"    ```\n    {f.code_snippet}\n    ```")

            md.append(f"- **Mandated Remediation**: {r.remediation}\n")

    if scorecard.ml_risk_prediction:
        md.append("---")
        md.append("## 4. Machine Learning Risk & Anomaly Assessment\n")
        ml_data = scorecard.ml_risk_prediction
        md.append(f"- **Predicted Compliance Probability**: `{ml_data.get('compliance_probability', 0.0):.1%}`")
        md.append(f"- **Anomaly Status**: `{ml_data.get('anomaly_status', 'NORMAL')}`")
        md.append(f"- **Anomaly Risk Index**: `{ml_data.get('anomaly_risk_index', 0.0):.2f}`")
        md.append(f"- **Assessment Message**: {ml_data.get('message', '')}\n")

    md.append("---")
    md.append("*Report generated by Bangladesh Bank MFS Automated Compliance Framework v1.0.*")

    full_report = "\n".join(md)
    if file_path:
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(full_report)
    return full_report
